language: node_js
node_js:
  - lts/*
cache: yarn
env:
  - SKIP_PREFLIGHT_CHECK=true
install:
  - yarn install
script:
  - lerna run format --stream
  - lerna run lint --stream
  - lerna run test --stream
  - lerna run test:e2e --stream
