const LOWERCASE_LETTERS = 'abcdefghijklmnopqrstuvwxyz';
const UPPERCASE_LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
const DIGITS = '0123456789';

export const CODE_LENGTH = 6;
export const ALPHABET = LOWERCASE_LETTERS + UPPERCASE_LETTERS + DIGITS;
